replicaCount: 1
image:
  repository: your-dev-image
  tag: dev
env:
  DOMAIN: dev.example.com
  API_URL: https://dev-api.example.com
  PORT: 8080
resources:
  limits:
    cpu: 250m
    memory: 256Mi
  requests:
    cpu: 100m
    memory: 128Mi
service:
  name: my-app-dev-service
  type: ClusterIP
  port: 80
  targetPort: 8080
