replicaCount: 3
image:
  repository: your-staging-image
  tag: staging
env:
  DOMAIN: staging.example.com
  API_URL: https://staging-api.example.com
  PORT: 8080
resources:
  limits:
    cpu: 500m
    memory: 512Mi
  requests:
    cpu: 250m
    memory: 256Mi
service:
  name: my-app-staging-service
  type: LoadBalancer
  port: 80
  targetPort: 8080
